/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function transform(value: any, casing: string): any
export declare function transformAsync(value: any, casing: string): Promise<unknown>
